services:
  tambouille-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - "8888:8888"
  tambouille-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8888
    restart: unless-stopped
    ports:
      - "3333:80"
